version: "3"

services:
  db:
    image: mariadb:10.9
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      TIME_ZONE: ${TIME_ZONE}
    volumes:
      - ./volume/db-data:/var/lib/mysql/
    networks:
      - orangehrm
    restart: always

  nginx:
    image: orangehrm/nginx
    build: nginx
    environment:
      TIME_ZONE: ${TIME_ZONE}
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
      - orangehrm

  php:
    image: orangehrm/php
    build: php
    environment:
      TIME_ZONE: ${TIME_ZONE}
    working_dir: ${REMOTE_SRC}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
      - orangehrm

networks:
  orangehrm: