version: "3.9"

services:
  db:
    image:  mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - ./volume/mysql:/var/lib/mysql
    restart: always
    networks:
      - orangehrm

  nginx:
    image: orangehrm/nginx
    build: nginx
    environment:
      TIME_ZONE: ${TIME_ZONE}
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
      - orangehrm

  php:
    image: orangehrm/php
    build: php
    environment:
      TIME_ZONE: ${TIME_ZONE}
    working_dir: ${REMOTE_SRC}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
      - orangehrm

networks:
  orangehrm: